### Cars
GET http://localhost:3000/api/cars

### Categories

GET http://localhost:3000/api/categories

### Reservation

GET http://localhost:3000/api/reservation

### Report

GET http://localhost:3000/api/report

### User

GET http://localhost:3000/api/user

### Admin

GET http://localhost:3000/api/admin