### Get All
GET http://localhost:3000/api/cars

### Add One
POST http://localhost:3000/api/cars
content-type: application/json

{
    "uuid": "df39a2e3-8f40-4615-86b2-2a0bf1958a8d",
    "brand": "Toyota",
    "model": "Tocoma",
    "year": 2014,
    "category": "4x4",
    "availability": true,
    "rentalPrice": 66500,
    "features": "Con aire acondicionado"
}

### Get One
GET http://localhost:3000/api/cars/df39a2e3-8f40-4615-86b2-2a0bf1958a8d


### Update One

PUT http://localhost:3000/api/cars/df39a2e3-8f40-4615-86b2-2a0bf1958a8d
content-type: application/json

{
    "rentalPrice": 15000
}

### Delete One

DELETE http://localhost:3000/api/cars/df39a2e3-8f40-4615-86b2-2a0bf1958a8d